name: Continuous Integration

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        container:
          - image: alpine:3
          - image: archlinux
          - image: artixlinux/base
          - image: debian:9
            env:
              DEBIAN_FRONTEND: noninteractive
          - image: debian:10
            env:
              DEBIAN_FRONTEND: noninteractive
          - image: elementary/docker:stable
            env:
              DEBIAN_FRONTEND: noninteractive
          - image: kalilinux/kali-rolling
            env:
              DEBIAN_FRONTEND: noninteractive
          - image: ubuntu:18.04
            env:
              DEBIAN_FRONTEND: noninteractive
          - image: ubuntu:20.04
            env:
              DEBIAN_FRONTEND: noninteractive
    steps:
      - uses: actions/checkout@v2
      - name: Install tar
        if: ${{ matrix.container.image == 'artixlinux/base' }}
        run: pacman -Sy && pacman -S tar
      - name: Run dev-container-install.sh
        run: ./tools/dev-container-install.sh

