name: Continuous Integration

on: [push]

jobs:
  install:
    runs-on: ${{ matrix.os }}
    container:
      image: ${{ matrix.image }}
    strategy:
      matrix:
        os:
          - ubuntu-18.04
          - macos-10.15
          - windows-2019
        image:
          - ubuntu:18.04
          - ubuntu:20.04
          - debian:9
          - debian:10
          - kalilinux/kali-rolling
    steps:
      - uses: actions/checkout@v2
      - name: Run dev-container-install.sh
        run: ./dev-container-install.sh

